version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs: 
  test:
    docker:
      - image: cimg/node:17.9.0
    steps:
      - checkout
      - run:
        name: Install dependencies
        command: yarn install
      - run:
        name: Run Tests
        command: yarn run test